In [1]:
import numpy as np

In [2]:
L = range(1000)
%timeit [i**2 for i in L]

71.5 μs ± 5.82 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

1.85 μs ± 276 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Create arrays

## Create 1 D array

In [4]:
# 1-D
a = np.array([1,2,3,4,5], dtype = float)
print(a.ndim)
print(a.shape)
print(a.dtype)

1
(5,)
float64


In [9]:
b = np.linspace(0,1,6)
b

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [10]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
f = np.diag(np.array([1,2,3,4,5]))
f

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [16]:
rng = np.random.default_rng(27446968)
j = rng.standard_normal(4)
j

array([-0.37001528, -0.95098944,  0.1087444 ,  1.87133713])

## 2 D

In [6]:
# 2-D
b = np.array([[0,1, 2],[3,4,5]])
print(b.ndim)
b.shape

2


(2, 3)

## 3 D

In [8]:
# 3-D
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c.ndim)
c.shape

3


(1, 3, 3)

# Numerical operations on arrays

In [22]:
arr = np.array([1,2,3,4])
arr + 1

array([2, 3, 4, 5])

In [23]:
2 ** arr

array([ 2,  4,  8, 16])

## All arithmetic operates elementwise

In [25]:
arr2 = np.ones(4)
arr2

array([1., 1., 1., 1.])

In [26]:
arr2 + 1

array([2., 2., 2., 2.])

In [27]:
arr - arr2

array([0., 1., 2., 3.])

In [28]:
arr * arr2

array([1., 2., 3., 4.])

In [29]:
arr3 = np.ones((3,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
arr3 * arr3         # NOT matrix multiplication

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
arr3 @ arr3         # Matrix multiplication

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [32]:
arr4 = np.array([1,2,3,4])
arr5 = np.array([4,2,2,4])
arr4 ==  arr5

array([False,  True, False,  True])

In [33]:
arr4 > arr5

array([False, False,  True, False])

### Logical operations

In [34]:
arr6 = np.array([1,1,0,0], dtype=bool)
arr7 = np.array([1,0,1,0], dtype=bool)
np.logical_or(arr6, arr7)

array([ True,  True,  True, False])

In [35]:
np.logical_and(arr6, arr7)

array([ True, False, False, False])

### Transcendental functions:

In [36]:
arr8 = np.arange(5)
np.sin(arr8)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [37]:
np.exp(arr8)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [38]:
np.log(np.exp(arr8))

array([0., 1., 2., 3., 4.])

### Transposition

In [40]:
arr9 = np.triu(np.ones((3,3)), 1)
arr9

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [41]:
arr9.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [42]:
arr10 = np.arange(9).reshape(3,3)
arr10

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
arr10.T[0,2] = 999
arr10.T

array([[  0,   3, 999],
       [  1,   4,   7],
       [  2,   5,   8]])

In [45]:
arr10

array([[  0,   1,   2],
       [  3,   4,   5],
       [999,   7,   8]])

## Basic reductions

In [46]:
tmp = np.array([1,2,3,4])
np.sum(tmp)

np.int64(10)

In [47]:
tmp = np.array([[1,1], [2,2]])
tmp

array([[1, 1],
       [2, 2]])

In [48]:
tmp.sum(axis=0)

array([3, 3])

In [49]:
tmp.sum(axis=1)

array([2, 4])

In [50]:
tmp = np.array([1,3,2])
tmp.min()

np.int64(1)

In [51]:
tmp.max()

np.int64(3)

In [52]:
tmp.argmin()

np.int64(0)

In [53]:
tmp.argmax()

np.int64(1)

In [54]:
np.all([True, True, False])

np.False_

In [55]:
np.any([True, True, False])

np.True_

In [56]:
tmp = np.zeros((100,100))
np.any(a != 0)

np.True_

In [57]:
tmp1 = np.array([1,2,3,1])
tmp2 = np.array([[1,2,3], [5,6,1]])
tmp1.mean()

np.float64(1.75)

In [59]:
np.median(tmp1)

np.float64(1.5)

In [60]:
tmp1.std()

np.float64(0.82915619758885)